### ISSUE TITLE
Launcher crash when downloading version (so far 1.18.31, which had no error but straight up just closed the launcher, 1.19.71 and 1.19.73 are the ones that don't seem to work, though I havent tried anything else.)

### ISSUE THREAD

**Issue by 0Nerd** [JiayiSoftware/JiayiLauncher#23]
[16:49:18] [JiayiSettings - Info]: Loaded settings.
[16:49:18] [ModCollection - Info]: Loaded mod collection at C:\Users\dpr39\AppData\Local\JiayiLauncher\Mods
[16:49:19] [JiayiSettings - Info]: Saved settings.
[16:49:19] [ThemeManager - Info]: Applied theme.
[16:49:19] [JiayiStats - Info]: Loaded stats.
[16:49:19] [Discord - Info]: Connected to GoldenMeerket#8554
[16:49:20] [Discord - Info]: Presence updated: Playing with no mods - on 1.19.83.1
[16:49:32] [TargetInvocationException - Error]: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Runtime.InteropServices.COMException (0x80040403): 0x80040403
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at JiayiLauncher.Features.Versions.RequestFactory.GetUpdateToken() in D:\projects\JiayiLauncher\JiayiLauncher\Features\Versions\RequestFactory.cs:line 46
   at JiayiLauncher.Features.Versions.RequestFactory.BuildUpdateTickets() in D:\projects\JiayiLauncher\JiayiLauncher\Features\Versions\RequestFactory.cs:line 64
   at JiayiLauncher.Features.Versions.RequestFactory.BuildHeader(String url, String methodName) in D:\projects\JiayiLauncher\JiayiLauncher\Features\Versions\RequestFactory.cs:line 78
   at JiayiLauncher.Features.Versions.RequestFactory.GetDownloadUrl(String updateId) in D:\projects\JiayiLauncher\JiayiLauncher\Features\Versions\RequestFactory.cs:line 99
   at JiayiLauncher.Features.Versions.VersionManager.DownloadVersion(MinecraftVersion version) in D:\projects\JiayiLauncher\JiayiLauncher\Features\Versions\VersionManager.cs:line 39
   at JiayiLauncher.Pages.Extra.FullVersionList.DownloadClicked(MinecraftVersion ver) in D:\projects\JiayiLauncher\JiayiLauncher\Pages\Extra\FullVersionList.razor:line 151
   at JiayiLauncher.Pages.Extra.FullVersionList.<>c__DisplayClass0_0.<<BuildRenderTree>b__8>d.MoveNext() in D:\projects\JiayiLauncher\JiayiLauncher\Pages\Extra\FullVersionList.razor:line 73
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Action workItem)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at JiayiLauncher.App.Main()

**Comment by notcarlton** [comment]
#22
